{
 "title": "oogabooga",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "label": "PDA #",
    "query": "SELECT pda FROM public.deliverytable"
   }
  ]
 },
 "panels": [
  {
   "title": "High Priority PDA",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pda,nomenclature,qty, status, delivery_window FROM deliverytable where high_priority is TRUE order by delivery_window"
    }
   ]
  },
  {
   "title": "Ground",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pda,nomenclature,qty, status, delivery_window FROM deliverytable where mode like 'ground'"
    }
   ]
  },
  {
   "title": "QTY DLVD/OTW",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    nomenclature as \"Nomenclature\",\r\n    SUM(CASE WHEN status = 'OTW' THEN qty ELSE 0 END) AS \"QTY OTW\",\r\n    SUM(CASE WHEN status = 'Delivered' THEN qty ELSE 0 END) AS \"QTY Delivered\"\r\nFROM \r\n    deliverytable\r\nGROUP BY \r\n    nomenclature\r\nORDER BY \r\n    nomenclature;"
    }
   ]
  },
  {
   "title": "Sea",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT pda,nomenclature,qty, status, delivery_window FROM deliverytable where mode like 'sea' ORDER BY delivery_window"
    }
   ]
  },
  {
   "title": "Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(status) FROM deliverytable GROUP BY status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Air",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT pda,nomenclature,qty, status, delivery_window FROM deliverytable where mode like 'air'"
    }
   ]
  },
  {
   "title": "Status of PDA Filtered by time frame",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT pda, edd, rdd, delivery_window as timestamp, status FROM deliverytable where $__timeFilter(delivery_window) ORDER BY status DESC "
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Out standing total of munition",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    -- CAST(pda AS INT),\r\n    pda,\r\n    nomenclature as \"Nomenclature\",\r\n    SUM(CASE WHEN status = 'OTW' THEN qty ELSE 0 END) AS \"QTY OTW\",\r\n    SUM(CASE WHEN status = 'Delivered' THEN qty ELSE 0 END) AS \"QTY Delivered\"\r\nFROM \r\n    deliverytable\r\nGROUP BY \r\n    pda, \r\n    nomenclature\r\nORDER BY \r\n    pda, \r\n    nomenclature;"
    }
   ]
  },
  {
   "title": "not delivered muntion totals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT nomenclature, SUM(qty) AS total_quantity\r\nFROM deliverytable \r\nwhere status Like 'Pending' or status like 'In Transit'\r\nGROUP BY nomenclature;"
    }
   ]
  },
  {
   "title": "delivered muntion totals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT nomenclature, SUM(qty) AS total_quantity\r\nFROM deliverytable \r\nwhere status LIKE 'Delivered'\r\nGROUP BY nomenclature;"
    }
   ]
  },
  {
   "title": "qty delivered",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT nomenclature, SUM(qty) AS total_quantity, delivery_window\r\nFROM deliverytable \r\nwhere status LIKE 'Delivered'\r\nGROUP BY nomenclature, delivery_window;"
    }
   ]
  },
  {
   "title": "bar",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(status), status FROM deliverytable GROUP BY status LIMIT 50 "
    }
   ]
  }
 ]
}