version: '2.2'

services:
  #Database Image (postgres)
  postgres:
    container_name: bipg_container
    #image: h20/bi-postgres
    build: .
    restart: always
    environment:
      POSTGRES_USER: shoc
      POSTGRES_PASSWORD: JustKeepSwimming
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  #Image of PGAdmin (web-based admin tool for postgres database)
  pgadmin:
    container_name: bipg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shoc@shoc.us
      PGADMIN_DEFAULT_PASSWORD: JustKeepSwimming
    links:
      - postgres
    ports:
      - "3031:80"


